version: "1"

services:
  database:
    image: mongo:5.0.8
    container_name: mongo-database
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    restart: always
    environment:
      - MONGO_DB='voll-solutions-challenge'
  api:
    image: node:16-slim
    container_name: voll-solutions-challenge-api
    ports:
      - 3001:3001
    volumes:
      - .:usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    restart: always
    environment:
      - PORT=3001
      - SALT=10
      - SECRET=teste
    links:
      - database